# Generated by Django 3.1.7 on 2021-03-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('MinValue', models.IntegerField(blank=True, null=True)),
                ('MaxValue', models.IntegerField(blank=True, null=True)),
                ('Result_Description', models.TextField()),
                ('Data_Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.data_source')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_ID', models.TextField()),
                ('Result_Name', models.TextField()),
                ('Source', models.TextField()),
                ('Result_Description', models.TextField()),
                ('Numeric_Result', models.IntegerField()),
                ('Patient_DOB', models.DateField()),
                ('Patient_Gender', models.TextField()),
                ('Date_Resulted', models.TextField()),
                ('Data_Source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.data_source')),
                ('Test_Name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.test_name')),
            ],
        ),
    ]
