# Generated by Django 3.1.7 on 2021-03-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_set',
            old_name='Data_Source_id',
            new_name='Data_Source',
        ),
        migrations.RenameField(
            model_name='data_set',
            old_name='Test_Name_id',
            new_name='Test_Name',
        ),
        migrations.RenameField(
            model_name='test_name',
            old_name='Data_Source_id',
            new_name='Data_Source',
        ),
    ]
