# Generated by Django 3.1.7 on 2021-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_test_name_result_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='Numeric_Result',
            field=models.FloatField(),
        ),
    ]
