# Generated by Django 3.1.7 on 2021-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210312_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_set',
            name='Numeric_Result',
            field=models.TextField(),
        ),
    ]
